name: mintlify docs


# WORKFLOW DISABLED
# This workflow is temporarily disabled via "if: false" at the job level
# and will be completely removed in a future PR as part of the mintlify
# cleanup task. It's preserved here temporarily for reference purposes.
# To re-enable, remove the "if: false" condition from the job.

on:
  push:
    branches: [main]
    paths:
      - "autogen/**"
      - "website/**"
      - ".github/workflows/deploy-website-mintlify.yml"
      - ".github/workflows/docs-check-broken-links.yml"
      - "scripts/broken-links-check.sh"
      - "scripts/docs_build.sh"
      - "scripts/docs_serve.sh"
      - ".muffet-excluded-links.txt"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  mintlify-release:
    # DISABLED: This workflow will be removed as part of the mintlify cleanup task
    if: false
    uses: ./.github/workflows/build-docs.yml
    with:
      python-version: "3.10"
      node-version: "18.x"
