name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Honkit and plugins
        run: |
          npm install -g honkit@latest
          npm install honkit@latest
          npm install gitbook-plugin-theme-default
          npm install gitbook-plugin-highlight
          
      - name: Build Documentation
        run: |
          npx honkit build ./ ./_book
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
